AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  ApplicationName:
    Type: String
  TrustedRepo:
    Type: String
    Description: A string to match against the repos you trust (orgname/reponame), can include wildcards


Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      ClientIdList:
        - sts.amazonaws.com

  OIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ApplicationName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${TrustedRepo}:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
